include: package:lint/analysis_options.yaml

analyzer:
  # enable-experiment:
    # - spread-collections
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    invalid_assignment: warning
